# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_auto_20190326_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circulo',
            new_name='Disco',
        ),
        migrations.RenameModel(
            old_name='Langui',
            new_name='Libro',
        ),
        migrations.RenameModel(
            old_name='Funcion',
            new_name='Zapatilla',
        ),
        migrations.DeleteModel(
            name='Concord',
        ),
        migrations.DeleteModel(
            name='Infrared',
        ),
        migrations.DeleteModel(
            name='Lebron',
        ),
        migrations.DeleteModel(
            name='Metamorfosis',
        ),
        migrations.DeleteModel(
            name='Noventa',
        ),
        migrations.DeleteModel(
            name='Teriyaki',
        ),
    ]
