# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20190328_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='image',
            field=models.ImageField(default=0, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(default=0, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='image',
            field=models.ImageField(default=0, upload_to='photos'),
        ),
    ]
