# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_auto_20190401_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
    ]
