# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_auto_20190401_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='file',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='libro',
            name='file',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='file',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
